name = "durable-prac"
main = "src/index.ts"
compatibility_date = "2024-01-17"


# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "CounterObject"

durable_objects.bindings = [
  { name = "COUNTER", class_name ="CounterObject" }
]


# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/learning/using-durable-objects#configure-durable-object-classes-with-migrations
[[migrations]]
tag = "v1"
new_classes = ["CounterObject"]
